# Generated by Django 4.0 on 2021-12-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер парковочного места')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(auto_created=True, unique=True, verbose_name='Номер бронирования')),
                ('start_time', models.DateTimeField(verbose_name='Время начала брони')),
                ('finish_time', models.DateTimeField(verbose_name='Время окончания брони')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking_systems.parking', verbose_name='Номер парковочного места')),
            ],
            options={
                'ordering': ['parking_space'],
            },
        ),
    ]
