# Generated by Django 4.0 on 2021-12-08 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='period',
        ),
        migrations.AddField(
            model_name='reservation',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время окончания брони'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала брони'),
        ),
    ]
