# Generated by Django 4.0 on 2021-12-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number',
        ),
    ]
